// IMPORTANT: This file is generated by scripts/fetch-external-dummy-data.ts
// Do not edit this file manually, as your changes will be overwritten.

import type { Product, Collection, Menu, Article, Cart } from './types';

export const dummyMenu: Menu[] = [
  {
    "title": "Home",
    "path": "/"
  },
  {
    "title": "All Products",
    "path": "/search"
  },
  {
    "title": "About Us (Dummy)",
    "path": "/about-dummy"
  },
  {
    "title": "Articles",
    "path": "/articles"
  }
];

// dummyCollections and dummyProducts have been removed.

export const dummyArticles: Article[] = [
  {
    "id": "gid://dummyjson/Post/1",
    "handle": "his-mother-had-always-taught-him",
    "title": "His mother had always taught him",
    "body": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
    "tags": [
      "history",
      "american",
      "crime"
    ],
    "seo": {
      "title": "His mother had always taught him",
      "description": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those w"
    },
    "author": {
      "name": "User 121"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  },
  {
    "id": "gid://dummyjson/Post/2",
    "handle": "he-was-an-expert-but-not-in-a-discipline",
    "title": "He was an expert but not in a discipline",
    "body": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
    "tags": [
      "french",
      "fiction",
      "english"
    ],
    "seo": {
      "title": "He was an expert but not in a discipline",
      "description": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream"
    },
    "author": {
      "name": "User 91"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  },
  {
    "id": "gid://dummyjson/Post/3",
    "handle": "dave-watched-as-the-forest-burned-up-on-the-hill",
    "title": "Dave watched as the forest burned up on the hill.",
    "body": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to round up the last of the pets. Dave went through his mental list of the most important papers and documents that they couldn't leave behind. He scolded himself for not having prepared these better in advance and hoped that he had remembered everything that was needed. He continued to wait for Marta to appear with the pets, but she still was nowhere to be seen.",
    "tags": [
      "magical",
      "history",
      "french"
    ],
    "seo": {
      "title": "Dave watched as the forest burned up on the hill.",
      "description": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to roun"
    },
    "author": {
      "name": "User 16"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  }
];

export const dummyCart: Cart = {
  "id": "gid://shopify/Cart/dummy-cart-id",
  "checkoutUrl": "#",
  "cost": {
    "subtotalAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    },
    "totalAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    },
    "totalTaxAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    }
  },
  "lines": {
    "edges": []
  },
  "totalQuantity": 0
};
