// IMPORTANT: This file is generated by scripts/fetch-external-dummy-data.ts
// Do not edit this file manually, as your changes will be overwritten.

import type { Product, Collection, Menu, Article, Cart } from './types';

export const dummyMenu: Menu[] = [
  {
    "title": "Home",
    "path": "/"
  },
  {
    "title": "All Products",
    "path": "/search"
  },
  {
    "title": "About Us (Dummy)",
    "path": "/about-dummy"
  },
  {
    "title": "Articles",
    "path": "/articles"
  }
];

export const dummyCollections: Collection[] = [
  {
    "handle": "summer-collection",
    "title": "Summer Collection",
    "description": "Bright and sunny items for summer.",
    "path": "/search/summer-collection",
    "updatedAt": "2025-05-26T06:59:12.534Z",
    "seo": {
      "title": "Summer Collection",
      "description": "Our summer items."
    },
    "featuredImage": {
      "url": "https://via.placeholder.com/400x300.png?text=Summer+Collection",
      "altText": "Image for Summer Collection",
      "width": 400,
      "height": 300
    }
  },
  {
    "handle": "featured-items",
    "title": "Featured Items",
    "description": "Hand-picked featured items.",
    "path": "/search/featured-items",
    "updatedAt": "2025-05-26T06:59:12.534Z",
    "seo": {
      "title": "Featured Items",
      "description": "Check out our featured items."
    },
    "featuredImage": {
      "url": "https://via.placeholder.com/400x300.png?text=Featured+Items",
      "altText": "Image for Featured Items",
      "width": 400,
      "height": 300
    }
  },
  {
    "handle": "",
    "title": "All",
    "description": "All products",
    "seo": {
      "title": "All",
      "description": "All products"
    },
    "path": "/search",
    "updatedAt": "2025-05-26T06:59:12.534Z"
  }
];

export const dummyProducts: Product[] = [
  {
    "id": "gid://dummyjson/Product/1",
    "handle": "essence-mascara-lash-princess",
    "availableForSale": true,
    "title": "Essence Mascara Lash Princess",
    "description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    "descriptionHtml": "<p>The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "9.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "9.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/1-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "9.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
      "altText": "Essence Mascara Lash Princess",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
            "altText": "Essence Mascara Lash Princess - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Essence Mascara Lash Princess",
      "description": "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula."
    },
    "tags": [
      "beauty",
      "mascara"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Essence",
    "category": "beauty"
  },
  {
    "id": "gid://dummyjson/Product/2",
    "handle": "eyeshadow-palette-with-mirror",
    "availableForSale": true,
    "title": "Eyeshadow Palette with Mirror",
    "description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    "descriptionHtml": "<p>The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "19.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "19.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/2-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "19.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
      "altText": "Eyeshadow Palette with Mirror",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
            "altText": "Eyeshadow Palette with Mirror - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Eyeshadow Palette with Mirror",
      "description": "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application."
    },
    "tags": [
      "beauty",
      "eyeshadow"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Glamour Beauty",
    "category": "beauty"
  },
  {
    "id": "gid://dummyjson/Product/3",
    "handle": "powder-canister",
    "availableForSale": true,
    "title": "Powder Canister",
    "description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    "descriptionHtml": "<p>The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "14.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "14.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/3-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "14.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
      "altText": "Powder Canister",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
            "altText": "Powder Canister - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Powder Canister",
      "description": "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish."
    },
    "tags": [
      "beauty",
      "face powder"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Velvet Touch",
    "category": "beauty"
  },
  {
    "id": "gid://dummyjson/Product/4",
    "handle": "red-lipstick",
    "availableForSale": true,
    "title": "Red Lipstick",
    "description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    "descriptionHtml": "<p>The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "12.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "12.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/4-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "12.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
      "altText": "Red Lipstick",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
            "altText": "Red Lipstick - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Red Lipstick",
      "description": "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish."
    },
    "tags": [
      "beauty",
      "lipstick"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Chic Cosmetics",
    "category": "beauty"
  },
  {
    "id": "gid://dummyjson/Product/5",
    "handle": "red-nail-polish",
    "availableForSale": true,
    "title": "Red Nail Polish",
    "description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    "descriptionHtml": "<p>The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "8.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "8.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/5-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "8.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
      "altText": "Red Nail Polish",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp",
            "altText": "Red Nail Polish - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Red Nail Polish",
      "description": "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home."
    },
    "tags": [
      "beauty",
      "nail polish"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Nail Couture",
    "category": "beauty"
  },
  {
    "id": "gid://dummyjson/Product/6",
    "handle": "calvin-klein-ck-one",
    "availableForSale": true,
    "title": "Calvin Klein CK One",
    "description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    "descriptionHtml": "<p>CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "49.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "49.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/6-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "49.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
      "altText": "Calvin Klein CK One",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp",
            "altText": "Calvin Klein CK One - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp",
            "altText": "Calvin Klein CK One - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp",
            "altText": "Calvin Klein CK One - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Calvin Klein CK One",
      "description": "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear."
    },
    "tags": [
      "fragrances",
      "perfumes"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Calvin Klein",
    "category": "fragrances"
  },
  {
    "id": "gid://dummyjson/Product/7",
    "handle": "chanel-coco-noir-eau-de",
    "availableForSale": true,
    "title": "Chanel Coco Noir Eau De",
    "description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    "descriptionHtml": "<p>Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "129.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "129.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/7-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "129.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
      "altText": "Chanel Coco Noir Eau De",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp",
            "altText": "Chanel Coco Noir Eau De - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp",
            "altText": "Chanel Coco Noir Eau De - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp",
            "altText": "Chanel Coco Noir Eau De - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Chanel Coco Noir Eau De",
      "description": "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions."
    },
    "tags": [
      "fragrances",
      "perfumes"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Chanel",
    "category": "fragrances"
  },
  {
    "id": "gid://dummyjson/Product/8",
    "handle": "dior-jadore",
    "availableForSale": true,
    "title": "Dior J'adore",
    "description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    "descriptionHtml": "<p>J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/8-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "89.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
      "altText": "Dior J'adore",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
            "altText": "Dior J'adore - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
            "altText": "Dior J'adore - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp",
            "altText": "Dior J'adore - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Dior J'adore",
      "description": "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication."
    },
    "tags": [
      "fragrances",
      "perfumes"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Dior",
    "category": "fragrances"
  },
  {
    "id": "gid://dummyjson/Product/9",
    "handle": "dolce-shine-eau-de",
    "availableForSale": true,
    "title": "Dolce Shine Eau de",
    "description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    "descriptionHtml": "<p>Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "69.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "69.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/9-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "69.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
      "altText": "Dolce Shine Eau de",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp",
            "altText": "Dolce Shine Eau de - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp",
            "altText": "Dolce Shine Eau de - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp",
            "altText": "Dolce Shine Eau de - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Dolce Shine Eau de",
      "description": "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent."
    },
    "tags": [
      "fragrances",
      "perfumes"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Dolce & Gabbana",
    "category": "fragrances"
  },
  {
    "id": "gid://dummyjson/Product/10",
    "handle": "gucci-bloom-eau-de",
    "availableForSale": true,
    "title": "Gucci Bloom Eau de",
    "description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    "descriptionHtml": "<p>Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "79.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "79.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/10-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "79.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
      "altText": "Gucci Bloom Eau de",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp",
            "altText": "Gucci Bloom Eau de - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp",
            "altText": "Gucci Bloom Eau de - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp",
            "altText": "Gucci Bloom Eau de - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Gucci Bloom Eau de",
      "description": "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent."
    },
    "tags": [
      "fragrances",
      "perfumes"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Gucci",
    "category": "fragrances"
  },
  {
    "id": "gid://dummyjson/Product/11",
    "handle": "annibale-colombo-bed",
    "availableForSale": true,
    "title": "Annibale Colombo Bed",
    "description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    "descriptionHtml": "<p>The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1899.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1899.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/11-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1899.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
      "altText": "Annibale Colombo Bed",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp",
            "altText": "Annibale Colombo Bed - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp",
            "altText": "Annibale Colombo Bed - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp",
            "altText": "Annibale Colombo Bed - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Annibale Colombo Bed",
      "description": "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom."
    },
    "tags": [
      "furniture",
      "beds"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Annibale Colombo",
    "category": "furniture"
  },
  {
    "id": "gid://dummyjson/Product/12",
    "handle": "annibale-colombo-sofa",
    "availableForSale": true,
    "title": "Annibale Colombo Sofa",
    "description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    "descriptionHtml": "<p>The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "2499.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "2499.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/12-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "2499.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
      "altText": "Annibale Colombo Sofa",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp",
            "altText": "Annibale Colombo Sofa - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp",
            "altText": "Annibale Colombo Sofa - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp",
            "altText": "Annibale Colombo Sofa - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Annibale Colombo Sofa",
      "description": "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room."
    },
    "tags": [
      "furniture",
      "sofas"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Annibale Colombo",
    "category": "furniture"
  },
  {
    "id": "gid://dummyjson/Product/13",
    "handle": "bedside-table-african-cherry",
    "availableForSale": true,
    "title": "Bedside Table African Cherry",
    "description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    "descriptionHtml": "<p>The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "299.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "299.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/13-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "299.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
      "altText": "Bedside Table African Cherry",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp",
            "altText": "Bedside Table African Cherry - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp",
            "altText": "Bedside Table African Cherry - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp",
            "altText": "Bedside Table African Cherry - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Bedside Table African Cherry",
      "description": "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance."
    },
    "tags": [
      "furniture",
      "bedside tables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Furniture Co.",
    "category": "furniture"
  },
  {
    "id": "gid://dummyjson/Product/14",
    "handle": "knoll-saarinen-executive-conference-chair",
    "availableForSale": true,
    "title": "Knoll Saarinen Executive Conference Chair",
    "description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    "descriptionHtml": "<p>The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "499.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "499.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/14-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "499.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
      "altText": "Knoll Saarinen Executive Conference Chair",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp",
            "altText": "Knoll Saarinen Executive Conference Chair - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp",
            "altText": "Knoll Saarinen Executive Conference Chair - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp",
            "altText": "Knoll Saarinen Executive Conference Chair - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Knoll Saarinen Executive Conference Chair",
      "description": "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design."
    },
    "tags": [
      "furniture",
      "office chairs"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Knoll",
    "category": "furniture"
  },
  {
    "id": "gid://dummyjson/Product/15",
    "handle": "wooden-bathroom-sink-with-mirror",
    "availableForSale": true,
    "title": "Wooden Bathroom Sink With Mirror",
    "description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    "descriptionHtml": "<p>The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "799.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "799.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/15-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "799.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
      "altText": "Wooden Bathroom Sink With Mirror",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp",
            "altText": "Wooden Bathroom Sink With Mirror - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp",
            "altText": "Wooden Bathroom Sink With Mirror - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp",
            "altText": "Wooden Bathroom Sink With Mirror - image 3",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Wooden Bathroom Sink With Mirror",
      "description": "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror."
    },
    "tags": [
      "furniture",
      "bathroom"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "brand": "Bath Trends",
    "category": "furniture"
  },
  {
    "id": "gid://dummyjson/Product/16",
    "handle": "apple",
    "availableForSale": true,
    "title": "Apple",
    "description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
    "descriptionHtml": "<p>Fresh and crisp apples, perfect for snacking or incorporating into various recipes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/16-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
      "altText": "Apple",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/apple/1.webp",
            "altText": "Apple - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Apple",
      "description": "Fresh and crisp apples, perfect for snacking or incorporating into various recipes."
    },
    "tags": [
      "fruits"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/17",
    "handle": "beef-steak",
    "availableForSale": true,
    "title": "Beef Steak",
    "description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
    "descriptionHtml": "<p>High-quality beef steak, great for grilling or cooking to your preferred level of doneness.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "12.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "12.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/17-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "12.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
      "altText": "Beef Steak",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp",
            "altText": "Beef Steak - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Beef Steak",
      "description": "High-quality beef steak, great for grilling or cooking to your preferred level of doneness."
    },
    "tags": [
      "meat"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/18",
    "handle": "cat-food",
    "availableForSale": true,
    "title": "Cat Food",
    "description": "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
    "descriptionHtml": "<p>Nutritious cat food formulated to meet the dietary needs of your feline friend.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "8.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "8.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/18-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "8.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/cat-food/thumbnail.webp",
      "altText": "Cat Food",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp",
            "altText": "Cat Food - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Cat Food",
      "description": "Nutritious cat food formulated to meet the dietary needs of your feline friend."
    },
    "tags": [
      "pet supplies",
      "cat food"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/19",
    "handle": "chicken-meat",
    "availableForSale": true,
    "title": "Chicken Meat",
    "description": "Fresh and tender chicken meat, suitable for various culinary preparations.",
    "descriptionHtml": "<p>Fresh and tender chicken meat, suitable for various culinary preparations.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "9.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "9.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/19-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "9.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/thumbnail.webp",
      "altText": "Chicken Meat",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp",
            "altText": "Chicken Meat - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp",
            "altText": "Chicken Meat - image 2",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Chicken Meat",
      "description": "Fresh and tender chicken meat, suitable for various culinary preparations."
    },
    "tags": [
      "meat"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/20",
    "handle": "cooking-oil",
    "availableForSale": true,
    "title": "Cooking Oil",
    "description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
    "descriptionHtml": "<p>Versatile cooking oil suitable for frying, sautéing, and various culinary applications.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "4.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "4.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/20-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "4.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
      "altText": "Cooking Oil",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp",
            "altText": "Cooking Oil - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Cooking Oil",
      "description": "Versatile cooking oil suitable for frying, sautéing, and various culinary applications."
    },
    "tags": [
      "cooking essentials"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/21",
    "handle": "cucumber",
    "availableForSale": true,
    "title": "Cucumber",
    "description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
    "descriptionHtml": "<p>Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1.49",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1.49",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/21-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1.49",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/cucumber/thumbnail.webp",
      "altText": "Cucumber",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp",
            "altText": "Cucumber - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Cucumber",
      "description": "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side."
    },
    "tags": [
      "vegetables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/22",
    "handle": "dog-food",
    "availableForSale": true,
    "title": "Dog Food",
    "description": "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
    "descriptionHtml": "<p>Specially formulated dog food designed to provide essential nutrients for your canine companion.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "10.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "10.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/22-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "10.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/dog-food/thumbnail.webp",
      "altText": "Dog Food",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp",
            "altText": "Dog Food - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Dog Food",
      "description": "Specially formulated dog food designed to provide essential nutrients for your canine companion."
    },
    "tags": [
      "pet supplies",
      "dog food"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/23",
    "handle": "eggs",
    "availableForSale": true,
    "title": "Eggs",
    "description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
    "descriptionHtml": "<p>Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "2.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "2.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/23-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "2.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
      "altText": "Eggs",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp",
            "altText": "Eggs - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Eggs",
      "description": "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast."
    },
    "tags": [
      "dairy"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/24",
    "handle": "fish-steak",
    "availableForSale": true,
    "title": "Fish Steak",
    "description": "Quality fish steak, suitable for grilling, baking, or pan-searing.",
    "descriptionHtml": "<p>Quality fish steak, suitable for grilling, baking, or pan-searing.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "14.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "14.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/24-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "14.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp",
      "altText": "Fish Steak",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp",
            "altText": "Fish Steak - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Fish Steak",
      "description": "Quality fish steak, suitable for grilling, baking, or pan-searing."
    },
    "tags": [
      "seafood"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/25",
    "handle": "green-bell-pepper",
    "availableForSale": true,
    "title": "Green Bell Pepper",
    "description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
    "descriptionHtml": "<p>Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1.29",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1.29",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/25-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1.29",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/thumbnail.webp",
      "altText": "Green Bell Pepper",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp",
            "altText": "Green Bell Pepper - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Green Bell Pepper",
      "description": "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes."
    },
    "tags": [
      "vegetables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/26",
    "handle": "green-chili-pepper",
    "availableForSale": true,
    "title": "Green Chili Pepper",
    "description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
    "descriptionHtml": "<p>Spicy green chili pepper, ideal for adding heat to your favorite recipes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "0.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "0.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/26-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "0.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/thumbnail.webp",
      "altText": "Green Chili Pepper",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp",
            "altText": "Green Chili Pepper - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Green Chili Pepper",
      "description": "Spicy green chili pepper, ideal for adding heat to your favorite recipes."
    },
    "tags": [
      "vegetables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/27",
    "handle": "honey-jar",
    "availableForSale": true,
    "title": "Honey Jar",
    "description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
    "descriptionHtml": "<p>Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "6.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "6.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/27-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "6.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
      "altText": "Honey Jar",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp",
            "altText": "Honey Jar - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Honey Jar",
      "description": "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food."
    },
    "tags": [
      "condiments"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/28",
    "handle": "ice-cream",
    "availableForSale": true,
    "title": "Ice Cream",
    "description": "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
    "descriptionHtml": "<p>Creamy and delicious ice cream, available in various flavors for a delightful treat.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "5.49",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "5.49",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/28-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "5.49",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp",
      "altText": "Ice Cream",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp",
            "altText": "Ice Cream - image 1",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp",
            "altText": "Ice Cream - image 2",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp",
            "altText": "Ice Cream - image 3",
            "width": 600,
            "height": 600
          }
        },
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp",
            "altText": "Ice Cream - image 4",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Ice Cream",
      "description": "Creamy and delicious ice cream, available in various flavors for a delightful treat."
    },
    "tags": [
      "desserts"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/29",
    "handle": "juice",
    "availableForSale": true,
    "title": "Juice",
    "description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
    "descriptionHtml": "<p>Refreshing fruit juice, packed with vitamins and great for staying hydrated.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "3.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "3.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/29-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "3.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp",
      "altText": "Juice",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/juice/1.webp",
            "altText": "Juice - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Juice",
      "description": "Refreshing fruit juice, packed with vitamins and great for staying hydrated."
    },
    "tags": [
      "beverages"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/30",
    "handle": "kiwi",
    "availableForSale": true,
    "title": "Kiwi",
    "description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
    "descriptionHtml": "<p>Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "2.49",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "2.49",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/30-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "2.49",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/kiwi/thumbnail.webp",
      "altText": "Kiwi",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp",
            "altText": "Kiwi - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Kiwi",
      "description": "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes."
    },
    "tags": [
      "fruits"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/31",
    "handle": "lemon",
    "availableForSale": true,
    "title": "Lemon",
    "description": "Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.",
    "descriptionHtml": "<p>Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "0.79",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "0.79",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/31-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "0.79",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/lemon/thumbnail.webp",
      "altText": "Lemon",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/lemon/1.webp",
            "altText": "Lemon - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Lemon",
      "description": "Zesty and tangy lemons, versatile for cooking, baking, or making refreshing beverages."
    },
    "tags": [
      "fruits"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/32",
    "handle": "milk",
    "availableForSale": true,
    "title": "Milk",
    "description": "Fresh and nutritious milk, a staple for various recipes and daily consumption.",
    "descriptionHtml": "<p>Fresh and nutritious milk, a staple for various recipes and daily consumption.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "3.49",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "3.49",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/32-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "3.49",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp",
      "altText": "Milk",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/milk/1.webp",
            "altText": "Milk - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Milk",
      "description": "Fresh and nutritious milk, a staple for various recipes and daily consumption."
    },
    "tags": [
      "dairy"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/33",
    "handle": "mulberry",
    "availableForSale": true,
    "title": "Mulberry",
    "description": "Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.",
    "descriptionHtml": "<p>Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "4.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "4.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/33-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "4.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/mulberry/thumbnail.webp",
      "altText": "Mulberry",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/mulberry/1.webp",
            "altText": "Mulberry - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Mulberry",
      "description": "Sweet and juicy mulberries, perfect for snacking or adding to desserts and cereals."
    },
    "tags": [
      "fruits"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/34",
    "handle": "nescafe-coffee",
    "availableForSale": true,
    "title": "Nescafe Coffee",
    "description": "Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.",
    "descriptionHtml": "<p>Quality coffee from Nescafe, available in various blends for a rich and satisfying cup.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "7.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "7.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/34-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "7.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp",
      "altText": "Nescafe Coffee",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/1.webp",
            "altText": "Nescafe Coffee - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Nescafe Coffee",
      "description": "Quality coffee from Nescafe, available in various blends for a rich and satisfying cup."
    },
    "tags": [
      "beverages",
      "coffee"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/35",
    "handle": "potatoes",
    "availableForSale": true,
    "title": "Potatoes",
    "description": "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.",
    "descriptionHtml": "<p>Versatile and starchy potatoes, great for roasting, mashing, or as a side dish.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "2.29",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "2.29",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/35-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "2.29",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/potatoes/thumbnail.webp",
      "altText": "Potatoes",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/potatoes/1.webp",
            "altText": "Potatoes - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Potatoes",
      "description": "Versatile and starchy potatoes, great for roasting, mashing, or as a side dish."
    },
    "tags": [
      "vegetables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/36",
    "handle": "protein-powder",
    "availableForSale": true,
    "title": "Protein Powder",
    "description": "Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.",
    "descriptionHtml": "<p>Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "19.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "19.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/36-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "19.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp",
      "altText": "Protein Powder",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/protein-powder/1.webp",
            "altText": "Protein Powder - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Protein Powder",
      "description": "Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins."
    },
    "tags": [
      "health supplements"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/37",
    "handle": "red-onions",
    "availableForSale": true,
    "title": "Red Onions",
    "description": "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
    "descriptionHtml": "<p>Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/37-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp",
      "altText": "Red Onions",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/red-onions/1.webp",
            "altText": "Red Onions - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Red Onions",
      "description": "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes."
    },
    "tags": [
      "vegetables"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/38",
    "handle": "rice",
    "availableForSale": true,
    "title": "Rice",
    "description": "High-quality rice, a staple for various cuisines and a versatile base for many dishes.",
    "descriptionHtml": "<p>High-quality rice, a staple for various cuisines and a versatile base for many dishes.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "5.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "5.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/38-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "5.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp",
      "altText": "Rice",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/rice/1.webp",
            "altText": "Rice - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Rice",
      "description": "High-quality rice, a staple for various cuisines and a versatile base for many dishes."
    },
    "tags": [
      "grains"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/39",
    "handle": "soft-drinks",
    "availableForSale": true,
    "title": "Soft Drinks",
    "description": "Assorted soft drinks in various flavors, perfect for refreshing beverages.",
    "descriptionHtml": "<p>Assorted soft drinks in various flavors, perfect for refreshing beverages.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "1.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/39-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "1.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp",
      "altText": "Soft Drinks",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/1.webp",
            "altText": "Soft Drinks - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Soft Drinks",
      "description": "Assorted soft drinks in various flavors, perfect for refreshing beverages."
    },
    "tags": [
      "beverages"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  },
  {
    "id": "gid://dummyjson/Product/40",
    "handle": "strawberry",
    "availableForSale": true,
    "title": "Strawberry",
    "description": "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.",
    "descriptionHtml": "<p>Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.</p>",
    "options": [],
    "priceRange": {
      "maxVariantPrice": {
        "amount": "3.99",
        "currencyCode": "USD"
      },
      "minVariantPrice": {
        "amount": "3.99",
        "currencyCode": "USD"
      }
    },
    "variants": {
      "edges": [
        {
          "node": {
            "id": "gid://dummyjson/ProductVariant/40-0",
            "title": "Default",
            "availableForSale": true,
            "selectedOptions": [],
            "price": {
              "amount": "3.99",
              "currencyCode": "USD"
            }
          }
        }
      ]
    },
    "featuredImage": {
      "url": "https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp",
      "altText": "Strawberry",
      "width": 300,
      "height": 300
    },
    "images": {
      "edges": [
        {
          "node": {
            "url": "https://cdn.dummyjson.com/product-images/groceries/strawberry/1.webp",
            "altText": "Strawberry - image 1",
            "width": 600,
            "height": 600
          }
        }
      ]
    },
    "seo": {
      "title": "Strawberry",
      "description": "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies."
    },
    "tags": [
      "fruits"
    ],
    "updatedAt": "2025-04-30T09:41:02.053Z",
    "category": "groceries"
  }
];

export const dummyArticles: Article[] = [
  {
    "id": "gid://dummyjson/Post/1",
    "handle": "his-mother-had-always-taught-him",
    "title": "His mother had always taught him",
    "body": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those who were less fortunate or who had less money than him. But the stupidity of the group of people he was talking to made him change his mind.",
    "tags": [
      "history",
      "american",
      "crime"
    ],
    "seo": {
      "title": "His mother had always taught him",
      "description": "His mother had always taught him not to ever think of himself as better than others. He'd tried to live by this motto. He never looked down on those w"
    },
    "author": {
      "name": "User 121"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  },
  {
    "id": "gid://dummyjson/Post/2",
    "handle": "he-was-an-expert-but-not-in-a-discipline",
    "title": "He was an expert but not in a discipline",
    "body": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream fell into it at the precise angle to form a perfect cone each and every time. It had taken years to perfect and he could now do it without even putting any thought behind it.",
    "tags": [
      "french",
      "fiction",
      "english"
    ],
    "seo": {
      "title": "He was an expert but not in a discipline",
      "description": "He was an expert but not in a discipline that anyone could fully appreciate. He knew how to hold the cone just right so that the soft server ice-cream"
    },
    "author": {
      "name": "User 91"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  },
  {
    "id": "gid://dummyjson/Post/3",
    "handle": "dave-watched-as-the-forest-burned-up-on-the-hill",
    "title": "Dave watched as the forest burned up on the hill.",
    "body": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to round up the last of the pets. Dave went through his mental list of the most important papers and documents that they couldn't leave behind. He scolded himself for not having prepared these better in advance and hoped that he had remembered everything that was needed. He continued to wait for Marta to appear with the pets, but she still was nowhere to be seen.",
    "tags": [
      "magical",
      "history",
      "french"
    ],
    "seo": {
      "title": "Dave watched as the forest burned up on the hill.",
      "description": "Dave watched as the forest burned up on the hill, only a few miles from her house. The car had been hastily packed and Marta was inside trying to roun"
    },
    "author": {
      "name": "User 16"
    },
    "createdAt": "2025-05-26T06:59:12.533Z",
    "updatedAt": "2025-05-26T06:59:12.533Z"
  }
];

export const dummyCart: Cart = {
  "id": "gid://shopify/Cart/dummy-cart-id",
  "checkoutUrl": "#",
  "cost": {
    "subtotalAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    },
    "totalAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    },
    "totalTaxAmount": {
      "amount": "0.00",
      "currencyCode": "USD"
    }
  },
  "lines": {
    "edges": []
  },
  "totalQuantity": 0
};
